data:
  image: busybox
  volumes:
    - ../code:/srv

web:
  build: docker/nginx
  volumes_from: [data]
  links:
    - fpm
  ports:
    - "80:80"

fpm:
  build: docker/php-fpm
  volumes_from: [data]
  links:
    - db
    - elasticsearch
  environment:
    - SYMFONY_ENV=dev

db:
  image: mysql:5.6
  volumes_from: [data]
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=symfony_dev
  ports:
    - "3306:3306"

elasticsearch:
    image: elasticsearch:1.6
    ports:
      - "9200:9200"

tools:
  build: docker/tools
  volumes_from: [data]
  environment:
    - SYMFONY_ENV=dev
  links:
    - db
    - elasticsearch
